CREATE OR REPLACE TABLE WORK_PRC_ELT.PRC_TEST10(
  ID NUMBER,
  ADDRESS VARCHAR(100),
  FLAG VARCHAR(1),
  FLAG2 VARCHAR(1),
  FLAG3 VARCHAR(1),
  FLAG4 VARCHAR(1)
  );

ALTER TABLE WORK_PRC_ELT.TEST80 ADD COLUMN FLAG4 VARCHAR(1);
