CREATE OR REPLACE TABLE WORK_UDP_ELT.STAGE_TABLE1(
  ID NUMBER ,
  NAME VARCHAR(100)
);

CREATE TABLE WORK_UDP_ELT.STAGE_TABLE2 AS SELECT * FROM WORK_UDP_ELT.STAGE_TABLE1;

ALTER TABLE WORK_UDP_ELT.STAGE_TABLE2 ADD COLUMN NAME VARCHAR(100);

